# For Fleet Free:
# - This file updates policies, queries, agent_options, and controls for all hosts.

# For Fleet Premium:
# - This file updates policies and queries that run on all hosts ("All teams").
# - Remove "controls" and add this to your YAML files in teams/ instead.

policies:
queries:
agent_options:
  path: ./lib/agent-options.yml
controls: # This cannot be set here and in no-team.yml
org_settings:
  fleet_desktop:
    transparency_url: https://catoftheday.com
  host_expiry_settings:
    host_expiry_enabled: true
    host_expiry_window: 30
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: AndrewsFleetServer
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
  features:
    enable_host_users: true
    enable_software_inventory: true
  webhook_settings:
    activities_webhook:
      enable_activities_webhook: true
      destination_url: "https://tamucs.webhook.office.com/webhookb2/77a455d7-804a-4400-85a0-6aea3a61d87e@68f381e3-46da-47b9-ba57-6f322b8f0da1/IncomingWebhook/88a63ca0201c4a74b889390a6c366850/e00e181d-8093-4a33-9d1a-67558616dc27/V2dKBvfEE9P7rwW5b_kQfL7Dv2KHNwYiDAaqT2v6STMrk1"
